"""add novels chapters reading_progresses

Revision ID: 81b158d0502b
Revises: c2c75098a151
Create Date: 2026-06-01 17:43:03.732442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b158d0502b'
down_revision: Union[str, Sequence[str], None] = 'c2c75098a151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_path', name='uq_novel_user_file_path')
    )
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_index(op.f('ix_novels_user_id'), 'novels', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('start_position', sa.BigInteger(), nullable=False),
    sa.Column('end_position', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_position > start_position', name='ck_chapter_end_position_greater'),
    sa.CheckConstraint('start_position >= 0', name='ck_chapter_start_position_positive'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_number', name='uq_chapter_novel_chapter_number')
    )
    op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.create_table('reading_progresses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.BigInteger(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='ck_reading_progress_percentage_range'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'novel_id', name='uq_reading_progress_user_novel')
    )
    op.create_index('ix_reading_progress_user_novel', 'reading_progresses', ['user_id', 'novel_id'], unique=False)
    op.create_index(op.f('ix_reading_progresses_chapter_id'), 'reading_progresses', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_reading_progresses_novel_id'), 'reading_progresses', ['novel_id'], unique=False)
    op.create_index(op.f('ix_reading_progresses_user_id'), 'reading_progresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_progresses_user_id'), table_name='reading_progresses')
    op.drop_index(op.f('ix_reading_progresses_novel_id'), table_name='reading_progresses')
    op.drop_index(op.f('ix_reading_progresses_chapter_id'), table_name='reading_progresses')
    op.drop_index('ix_reading_progress_user_novel', table_name='reading_progresses')
    op.drop_table('reading_progresses')
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_user_id'), table_name='novels')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
