"""add user_settings table

Revision ID: e1b42610b358
Revises: 2c65267e41e3
Create Date: 2026-06-05 18:38:24.446828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b42610b358'
down_revision: Union[str, Sequence[str], None] = '2c65267e41e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme_mode', sa.String(length=20), nullable=False),
    sa.Column('bg_color', sa.String(length=9), nullable=False),
    sa.Column('bg_opacity', sa.REAL(), nullable=False),
    sa.Column('font_family', sa.String(length=500), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('line_height', sa.REAL(), nullable=False),
    sa.Column('paragraph_spacing', sa.Integer(), nullable=False),
    sa.Column('reader_max_width', sa.Integer(), nullable=False),
    sa.Column('first_line_indent', sa.Boolean(), nullable=False),
    sa.Column('default_reformat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
